export const Menu = [
  {
    price: 15.00,
    rating: 4,
    name: "soup",
    specialName: "Tomato Soup",
    explanation:"It is served with bread, arugula, lemon and pickled pepper.",
    image: "https://cdn.yemek.com/mncrop/940/625/uploads/2015/01/anti-eflamatuar-corba-tarifi.jpg",
  },
  {
    price: 10.00,
    rating: 5,
    name: "soup",
    specialName: "Yoghurt Soup",
    explanation:"It is served with bread, arugula, lemon and pickled pepper.",
    image: "https://cdn.yemek.com/mncrop/940/625/uploads/2020/04/kolay-pirincli-yogurt-corbasi.jpg",
  },
  {
    price: 10.00,
    rating: 4,
    name: "soup",
    specialName: "Lentil Soup",
    explanation:"It is served with bread, arugula, lemon and pickled pepper.",
    image: "https://cdn.yemek.com/mnresize/940/940/uploads/2019/10/duduklu-tencerede-mercimek-corbasi-one-cikan.jpg",
  },
  {
    price: 15.00,
    rating: 4,
    name: "soup",
    specialName: "Mushroom Soup",
    explanation:"It is served with bread, arugula, lemon and pickled pepper.",
    image: "https://realfood.tesco.com/media/images/RFO-1400x919-MushroomSoup-53f74338-aa39-4c34-b5da-2858937db4c5-0-1400x919.jpg",
  },
  {
    price: 13.00,
    rating: 5,
    name: "soup",
    specialName: "Broccoli Soup",
    explanation:"It is served with bread, arugula, lemon and pickled pepper.",
    image: "https://realfood.tesco.com/media/images/roasted-spiced-broccoli-and-lemon-soup-1400x919-16-f96f22b6-56b3-4d31-80e0-4e1b6514cc25-0-1400x919.jpg",
  },
  {
    price: 50.00,
    rating: 4,
    name: "meal",
    specialName: "Kebab",
    explanation:"It is served with rice pilaf, tomatoes, peppers, onions and greens.",
    image: "https://cdn.yemek.com/mnresize/1250/833/uploads/2021/03/sipsak-tabakalar2-yemekcom.jpg",
  },
  {
    price: 15.00,
    rating: 3,
    name: "meal",
    specialName: "Lahmacun",
    explanation:"It is served with salad",
    image: "https://cdn.yemek.com/mncrop/940/625/uploads/2020/04/lahmacun-yeni-one-cikan.jpg",
  },
  {
    price: 30.00,
    rating: 2,
    name: "meal",
    specialName: "Chicken Saute",
    explanation:"It is served with bulgur pilaf, shepherd's salad and roasted tomatoes.",
    image: "https://cdn.yemek.com/mncrop/940/625/uploads/2016/04/sebzeli-tavuk-sote.jpg",
  },
  {
    price: 40.00,
    rating: 4,
    name: "meal",
    specialName: "Sauteed Meat",
    explanation:"It is served with bulgur pilaf, shepherd's salad and roasted tomatoes.",
    image: "https://ykv.s3.eu-central-1.amazonaws.com/img/tarif/ogt/et-sote.jpg",
  },
  {
    price: 25.00,
    rating: 3,
    name: "meal",
    specialName: "Beans and Rice",
    explanation:"It is served with pickles",
    image: "https://fasulye.gen.tr/images/kuru-fasulye-pilav(1).jpg",
  },

  {
    price: 20.00,
    rating: 4,
    name: "salad",
    specialName: "Mediterranean Salad",
    explanation:"It is served with its special sauce",
    image: "https://ykv.s3.eu-central-1.amazonaws.com/img/tarif/mgt/beyaz-peynirli-akdeniz-salatasi-4.jpg",
  },
  {
    price: 22.00,
    rating: 3,
    name: "salad",
    specialName: "Shepherd Salad",
    explanation:"It is served with its special sauce",
    image: "https://img-s1.onedio.com/id-612febad3eb79c54149ef99e/rev-0/w-600/h-450/f-jpg/s-284983f773054f3b0643109d1873cf9e3633bdbc.jpg",
  },
  {
    price: 17.00,
    rating: 4,
    name: "salad",
    specialName: "Lettuce Salad",
    explanation:"It is served with its special sauce",
    image: "http://www.harikalarmutfagi.com.tr/image/large/data/293-3345_marul_salatasi.jpg",
  },
  {
    price: 45.00,
    rating: 4,
    name: "fast food",
    specialName: "Hamburger",
    explanation:"It is served with french fries",
    image: "https://cdn.yemek.com/mnresize/940/940/uploads/2016/05/ev-yapimi-hamburger.jpg",
  },
  {
    price: 35.00,
    rating: 3,
    name: "fast food",
    specialName: "Pizza",
    explanation:"It is served with french fries",
    image: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/11/ev-yapimi-pizza-7-tarifi.jpg",
  },
  {
    price: 19.00,
    rating: 4,
    name: "fast food",
    specialName: "Fried Potatoes",
    explanation:"It is served with ketchup and mayonnaise",
    image: "https://www.muhsinbagdadioglu.com/wp-content/uploads/2019/05/Patates-K%C4%B1zartmas%C4%B1-1-1280x720.jpg",
  },
  {
    price: 20.00,
    rating: 3,
    name: "dessert",
    specialName: "Baklava",
    explanation:"Served with ice cream",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Baklava%281%29.png",
  },
  {
    price: 15.00,
    rating: 4,
    name: "dessert",
    specialName: "Rice Pudding",
    explanation:"Made from fresh milk, served with cinnamon",
    image: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/11/firin-sutlac-son-tarifi.jpg",
  },
  {
    price: 25.00,
    rating: 2,
    name: "dessert",
    specialName: "Souffle",
    explanation:"Served hot with liquid chocolate.",
    image: "https://i20.haber7.net/resize/1240x720//haber/haber7/photos/2022/03/mikrodalgada_sufle_nasil_yapilir_90_saniyede_yumurtasiz_sufle_tarifi_1642764473_6676.jpg",
  },
  {
    price: 23.00,
    rating: 1,
    name: "dessert",
    specialName: "Tiramisu",
    explanation:"It is an Italian dessert whose main ingredient is mascarpone cheese and chocolate",
    image: "https://i.lezzet.com.tr/images-xxlarge-recipe/tiramisu-744b0547-1e41-435a-8614-1f593872055d.jpg",
  },
  {
    price: 5.00,
    rating: 1,
    name: "drink",
    specialName: "Water",
    explanation:"500 ml of water",
    image: "https://cf.kizlarsoruyor.com/q4074585/300cd4b1-dbc4-46e8-953d-507917a7dbc9.jpg",
  },
  {
    price: 18.00,
    rating: 5,
    name: "drink",
    specialName: "Lemonade",
    explanation:"made from fresh lemons and served with mint",
    image: "https://i.lezzet.com.tr/images-xxlarge-recipe/ev-yapimi-konsantre-limonata-01e50b99-5890-411f-a4c2-997a71e8a5cc.jpg",
  },
  {
    price: 10.00,
    rating: 4,
    name: "drink",
    specialName: "Coke",
    explanation:"330 ml of coke",
    image: "https://bizegorelezzetler.com/wp-content/uploads/2021/02/bir-bardak-kola-kac-kalori-kola-kilo-aldirir-mi-kilo-yapar-mi.jpg",
  },
  {
    price: 22.00,
    rating: 5,
    name: "drink",
    specialName: "Hot Chocolate",
    explanation:"It is made from high quality chocolates, served with cream.",
    image: "https://i4.hurimg.com/i/hurriyet/75/866x494/5fc798b4d3806c07f04bcf3b.jpg",
  },
  {
    price: 13.00,
    rating: 4,
    name: "drink",
    specialName: "Coffee",
    explanation:"Coffees are carefully prepared from freshly ground coffee beans",
    image: "https://media.istockphoto.com/photos/cup-of-cafe-latte-with-coffee-beans-and-cinnamon-sticks-picture-id505168438?k=20&m=505168438&s=170667a&w=0&h=QPNicbKAMFehsfYNhSWEmtA_fulyX_VuKbgalU8YsH4=",
  },
];